databases:
  - name: tokoyu
    databaseName: tokoyu
    user: tokoyu
    region: singapore

services:
  - type: web
    name: tokoyu
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tokoyu
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

